export const UNIT_TYPES_MAPPED = {
    'C62': 'Adet',
    'B32': 'Kg/Metre Kare',
    'CCT': 'Ton Başına Taşıma Kapasitesi',
    'PR': 'Çift',
    'D30': 'Brüt Kalori Değeri',
    'D40': 'Bin Litre',
    'GFI': 'Fissile İzotop Gramı',
    'GRM': 'Gram',
    'GT': 'Gross Ton',
    'CEN': 'Yüz Adet',
    'KPO': 'Kilogram Potasyum Oksit',
    'MND': 'Kurutulmuş Net Ağırlıklı Kilogramı',
    '3I': 'Kilogram-Adet',
    'KFO': 'Difosfor Pentaoksit Kilogramı',
    'KGM': 'Kilogram',
    'KHY': 'Hidrojen Peroksit Kilogramı',
    'KMA': 'Metil Aminlerin Kilogramı',
    'KNI': 'Azotun Kilogramı',
    'KPH': 'Kilogram Potasyum Hidroksit',
    'KSD': '%90 Kuru Ürün Kilogramı',
    'KSH': 'Sodyum Hidroksit Kilogramı',
    'KUR': 'Uranyum Kilogramı',
    'D32': 'Terawatt Saat',
    'GWH': 'Gigawatt Saat',
    'MWH': 'Megawatt Saat (1000 kW.h)',
    'KWH': 'Kilowatt Saat',
    'KWT': 'Kilowatt',
    'LPA': 'Saf Alkol Litresi',
    'LTR': 'Litre',
    'MTK': 'Metre Kare',
    'DMK': 'Desimetre Kare',
    'MTQ': 'Metre Küp',
    'MTR': 'Metre',
    'NCL': 'Hücre Adedi',
    'CTM': 'Karat',
    'SM3': 'Standart Metreküp',
    'R9': 'Bin Metre Küp',
    'SET': 'Set',
    'T3': 'Bin Adet',
    'TON': 'Ton',
    'TNE': 'Kuru Ton',
    'MIN': 'Dakika',
    'HUR': 'Saat',
    'DAY': 'Gün',
    'WEE': 'Hafta',
    'MON': 'Ay',
}

export const UNIT_TYPES = Object.entries(UNIT_TYPES_MAPPED).map(([code, name]) => ({ value: code, text: name }));