# version: '3.5'

services:
    mariadb:
        image: mariadb
        environment:
            # MYSQL_ROOT_PASSWORD: <your_root_password_here>
            MYSQL_USER: postral
            MYSQL_PASSWORD: postral
            MARIADB_DATABASE: postral_epos
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        ports:
            - '3306:3306'
        volumes:
            - './init.sql:/docker-entrypoint-initdb.d/1.sql'

    # engine5:
    #     image: hcangunduz/engine5:0.0.9-alpha
    #     ports:
    #         - 3535:3535
