/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { AccountDTO } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class AccountNewControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async fetchAll(name: string | undefined, legalIdentity: string | undefined, type: "INDIVIDUAL" | "COMMERCIAL" | undefined, deactivated: "NOT_DEACTIVATED" | "ONLY_DEACTIVATED" | "ALL" | undefined, taxOffice: string | undefined, ownerUserId: string | undefined, entityOwnershipGroupId: string | undefined, entityIds: string[] | undefined, admin: "true" | "false" | undefined): Promise<AccountDTO[]> {
    let urlAltered = this.interceptUrl("api/account") + '?' + `name=${name}` + '&' + `legalIdentity=${legalIdentity}` + '&' + `type=${type}` + '&' + `deactivated=${deactivated}` + '&' + `taxOffice=${taxOffice}` + '&' + `ownerUserId=${ownerUserId}` + '&' + `entityOwnershipGroupId=${entityOwnershipGroupId}` + '&' + `entityIds=${entityIds}` + '&' + `admin=${admin}`;
    return firstValueFrom(this.http.get<AccountDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async search(name: string | undefined, legalIdentity: string | undefined, type: "INDIVIDUAL" | "COMMERCIAL" | undefined, deactivated: "NOT_DEACTIVATED" | "ONLY_DEACTIVATED" | "ALL" | undefined, taxOffice: string | undefined, ownerUserId: string | undefined, entityOwnershipGroupId: string | undefined, entityIds: string[] | undefined, admin: "true" | "false" | undefined): Promise<AccountDTO> {
    let urlAltered = this.interceptUrl("api/account/_search") + '?' + `name=${name}` + '&' + `legalIdentity=${legalIdentity}` + '&' + `type=${type}` + '&' + `deactivated=${deactivated}` + '&' + `taxOffice=${taxOffice}` + '&' + `ownerUserId=${ownerUserId}` + '&' + `entityOwnershipGroupId=${entityOwnershipGroupId}` + '&' + `entityIds=${entityIds}` + '&' + `admin=${admin}`;
    return firstValueFrom(this.http.get<AccountDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchOne(id: String): Promise<AccountDTO> {
    let urlAltered = this.interceptUrl("api/account/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<AccountDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async add(requestBody: AccountDTO): Promise<AccountDTO> {
    let urlAltered = this.interceptUrl("api/account");
    return firstValueFrom(this.http.post<AccountDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async edit(requestBody: AccountDTO): Promise<AccountDTO> {
    let urlAltered = this.interceptUrl("api/account");
    return firstValueFrom(this.http.put<AccountDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async remove(id: String): Promise<void> {
    let urlAltered = this.interceptUrl("api/account/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


}
