/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { AccountAddressDto } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class AddressControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async fetchAll(id: string | undefined, name: string | undefined, admin: "true" | "false" | undefined, ownerUserId: string | undefined, entityOwnershipGroupId: string | undefined): Promise<AccountAddressDto[]> {
    let urlAltered = this.interceptUrl("api/address") + '?' + `id=${id}` + '&' + `name=${name}` + '&' + `admin=${admin}` + '&' + `ownerUserId=${ownerUserId}` + '&' + `entityOwnershipGroupId=${entityOwnershipGroupId}`;
    return firstValueFrom(this.http.get<AccountAddressDto[]>(urlAltered).pipe(map(r => r.data)));
  }


  async search(id: string | undefined, name: string | undefined, admin: "true" | "false" | undefined, ownerUserId: string | undefined, entityOwnershipGroupId: string | undefined): Promise<AccountAddressDto> {
    let urlAltered = this.interceptUrl("api/address/_search") + '?' + `id=${id}` + '&' + `name=${name}` + '&' + `admin=${admin}` + '&' + `ownerUserId=${ownerUserId}` + '&' + `entityOwnershipGroupId=${entityOwnershipGroupId}`;
    return firstValueFrom(this.http.get<AccountAddressDto>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchOne(id: string): Promise<AccountAddressDto> {
    let urlAltered = this.interceptUrl("api/address/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<AccountAddressDto>(urlAltered).pipe(map(r => r.data)));
  }


  async add(requestBody: AccountAddressDto): Promise<AccountAddressDto> {
    let urlAltered = this.interceptUrl("api/address");
    return firstValueFrom(this.http.post<AccountAddressDto>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async edit(requestBody: AccountAddressDto): Promise<AccountAddressDto> {
    let urlAltered = this.interceptUrl("api/address");
    return firstValueFrom(this.http.put<AccountAddressDto>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async remove(id: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/address/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


}
