/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class AdminOperationsControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async encryptSensitiveData(requestBody: void): Promise<void> {
    let urlAltered = this.interceptUrl("api/admin-operations/encrypt-sensitive-data");
    return firstValueFrom(this.http.post<void>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async decryptSensitiveData(requestBody: void): Promise<void> {
    let urlAltered = this.interceptUrl("api/admin-operations/decrypt-sensitive-data");
    return firstValueFrom(this.http.post<void>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async runBilling(requestBody: void): Promise<void> {
    let urlAltered = this.interceptUrl("api/admin-operations/run-billing");
    return firstValueFrom(this.http.post<void>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


}
