/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { AdminSettingsDto } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class AdminSettingsControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async getAdminSettings(): Promise<AdminSettingsDto> {
    let urlAltered = this.interceptUrl("api/admin-settings");
    return firstValueFrom(this.http.get<AdminSettingsDto>(urlAltered).pipe(map(r => r.data)));
  }


  async updateAdminSettings(requestBody: { id: undefined | string; sellerPaysPaymentServiceFee: undefined | false | true; comissionsCalculatedFromNet: undefined | false | true; comissionItemTaxId: undefined | string; comissionItemTax: undefined | { id: string; taxName: string; isPublic: boolean; variations: import("/home/huseyin/dev/tk-ubs/postralmona/libs/postral-entities/src/index").ItemTaxVariation[]; }; billingAccountId: undefined | string; billingAccount: undefined | { id: string; name: string; legalIdentity: string; type: "INDIVIDUAL" | "COMMERCIAL"; defaultAddressId: undefined | string; defaultAddress: undefined | { id: string; name: string; buildingNumber: string | undefined; buildingName: string | undefined; room: string | undefined; floor: string | undefined; blockName: string | undefined; streetName: string; additionalStreetName: string | undefined; district: string | undefined; citySubdivisionName: string; cityName: string; postalZone: string; region: string | undefined; postbox: string | undefined; country: string; countrySubentity: string | undefined; countrySubentityCode: string | undefined; addressFormatCode: string | undefined; addressTypeCode: string | undefined; department: string | undefined; markAttention: string | undefined; markCare: string | undefined; plotIdentification: string | undefined; cityCode: string | undefined; inhaleName: string | undefined; timezone: string | undefined; }; deactivated: boolean; bankName: undefined | string; bankIban: undefined | string; bankBic: undefined | string; bankSwift: undefined | string; taxOffice: undefined | string; }; billingDays: undefined | number[]; createdAt: undefined | { getVarDate: () => VarDate; }; updatedAt: undefined | Date; }): Promise<AdminSettingsDto> {
    let urlAltered = this.interceptUrl("api/admin-settings");
    return firstValueFrom(this.http.put<AdminSettingsDto>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


}
