/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { SearchResult } from '@ubs-platform/crud-base-common';

import { AppComissionDTO } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class AppComissionControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async findAllSearch(page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined): Promise<SearchResult<AppComissionDTO>> {
    let urlAltered = this.interceptUrl("api/app-comission/_search") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}`;
    return firstValueFrom(this.http.get<SearchResult<AppComissionDTO>>(urlAltered).pipe(map(r => r.data)));
  }


  async update(requestBody: AppComissionDTO): Promise<AppComissionDTO> {
    let urlAltered = this.interceptUrl("api/app-comission");
    return firstValueFrom(this.http.put<AppComissionDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async delete(id: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/app-comission/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


}
