/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:37:12.947Z
 */
import { UserAuth, UserAuthSuccess } from '@ubs-platform/users-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class AuthControllerService {
  readonly basePath = process.env['TESTO_UBS_USERS_URL'] || '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async authenticate(requestBody: UserAuth): Promise<UserAuthSuccess> {
    let urlAltered = this.interceptUrl("api/auth");
    return firstValueFrom(this.http.post<UserAuthSuccess>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async getSelfUser(): Promise<any> {
    let urlAltered = this.interceptUrl("api/auth");
    return firstValueFrom(this.http.get<any>(urlAltered).pipe(map(r => r.data)));
  }


  async hasRole(requestBody: string[]): Promise<false | true> {
    let urlAltered = this.interceptUrl("api/auth/has-role");
    return firstValueFrom(this.http.post<false | true>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async logout(requestBody: void): Promise<void> {
    let urlAltered = this.interceptUrl("api/auth/logout");
    return firstValueFrom(this.http.post<void>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


}
