/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { ItemListCalculationInputDto, ItemListCalculationDto } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class CalculationControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async calculateTotalAmount(requestBody: ItemListCalculationInputDto): Promise<ItemListCalculationDto> {
    let urlAltered = this.interceptUrl("api/calculation/total-amount");
    return firstValueFrom(this.http.post<ItemListCalculationDto>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


}
