/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { PaymentChannelStatusDTO } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class DummyEcommercePaymentChannelControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async startPaymentOperation(requestBody: void): Promise<PaymentChannelStatusDTO> {
    let urlAltered = this.interceptUrl("api/dummy-ecommerce-payment-channel/operation");
    return firstValueFrom(this.http.post<PaymentChannelStatusDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async getPaymentOperationDummyPage(operationId: string, redirectUrlBackToApp: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/dummy-ecommerce-payment-channel/operation/:operationId").replace(':operationId', operationId + '') + '?' + `redirectUrlBackToApp=${redirectUrlBackToApp}`;
    return firstValueFrom(this.http.get<void>(urlAltered).pipe(map(r => r.data)));
  }


  async setPaymentStatusAndRedirect(operationId: string, set: "COMPLETED" | "FAILED", redirectUrlBackToApp: string): Promise<{ status: "COMPLETED" | "FAILED"; }> {
    let urlAltered = this.interceptUrl("api/dummy-ecommerce-payment-channel/operation/:operationId/status/:set").replace(':operationId', operationId + '').replace(':set', set + '') + '?' + `redirectUrlBackToApp=${redirectUrlBackToApp}`;
    return firstValueFrom(this.http.get<{ status: "COMPLETED" | "FAILED"; }>(urlAltered).pipe(map(r => r.data)));
  }


  async checkPaymentStatusAndRedirect(operationId: string, redirectUrlBackToApp: string): Promise<never> {
    let urlAltered = this.interceptUrl("api/dummy-ecommerce-payment-channel/operation/:operationId/status").replace(':operationId', operationId + '') + '?' + `redirectUrlBackToApp=${redirectUrlBackToApp}`;
    return firstValueFrom(this.http.get<never>(urlAltered).pipe(map(r => r.data)));
  }


  async kDialogTestPut(requestBody: any): Promise<{ message: string; receivedBody: any; }> {
    let urlAltered = this.interceptUrl("api/dummy-ecommerce-payment-channel/kdialog");
    return firstValueFrom(this.http.put<{ message: string; receivedBody: any; }>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async kDialogTestPost(requestBody: any): Promise<{ message: string; receivedBody: any; }> {
    let urlAltered = this.interceptUrl("api/dummy-ecommerce-payment-channel/kdialog");
    return firstValueFrom(this.http.post<{ message: string; receivedBody: any; }>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async kDialogTestGet(query: any): Promise<{ message: string; receivedBody: any; }> {
    let urlAltered = this.interceptUrl("api/dummy-ecommerce-payment-channel/kdialog") + '?' + `query=${query}`;
    return firstValueFrom(this.http.get<{ message: string; receivedBody: any; }>(urlAltered).pipe(map(r => r.data)));
  }


}
