/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { InvoiceCreateDTO, InvoiceDTO, InvoiceUpdateDTO } from '@tk-postral/payment-common';
import { RawSearchResult, SearchResult } from '@ubs-platform/crud-base-common';



import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class InvoiceControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async create(requestBody: InvoiceCreateDTO): Promise<InvoiceDTO> {
    let urlAltered = this.interceptUrl("api/invoice");
    return firstValueFrom(this.http.post<InvoiceDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async findById(id: string): Promise<InvoiceDTO> {
    let urlAltered = this.interceptUrl("api/invoice/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<InvoiceDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async update(id: string, requestBody: InvoiceUpdateDTO): Promise<InvoiceDTO> {
    let urlAltered = this.interceptUrl("api/invoice/:id").replace(':id', id + '');
    return firstValueFrom(this.http.put<InvoiceDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async delete(id: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/invoice/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchAll(page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined, paymentId: string | undefined, sellerPaymentOrderId: string | undefined, invoiceNumber: string | undefined, status: string | undefined, uploadedByUserId: string | undefined, dateFrom: Date | undefined, dateTo: Date | undefined, finalized: boolean | "true" | "false" | undefined): Promise<InvoiceDTO[]> {
    let urlAltered = this.interceptUrl("api/invoice") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}` + '&' + `paymentId=${paymentId}` + '&' + `sellerPaymentOrderId=${sellerPaymentOrderId}` + '&' + `invoiceNumber=${invoiceNumber}` + '&' + `status=${status}` + '&' + `uploadedByUserId=${uploadedByUserId}` + '&' + `dateFrom=${dateFrom}` + '&' + `dateTo=${dateTo}` + '&' + `finalized=${finalized}`;
    return firstValueFrom(this.http.get<InvoiceDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async search(page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined, paymentId: string | undefined, sellerPaymentOrderId: string | undefined, invoiceNumber: string | undefined, status: string | undefined, uploadedByUserId: string | undefined, dateFrom: Date | undefined, dateTo: Date | undefined, finalized: boolean | "true" | "false" | undefined): Promise<SearchResult<InvoiceDTO>> {
    let urlAltered = this.interceptUrl("api/invoice/_search") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}` + '&' + `paymentId=${paymentId}` + '&' + `sellerPaymentOrderId=${sellerPaymentOrderId}` + '&' + `invoiceNumber=${invoiceNumber}` + '&' + `status=${status}` + '&' + `uploadedByUserId=${uploadedByUserId}` + '&' + `dateFrom=${dateFrom}` + '&' + `dateTo=${dateTo}` + '&' + `finalized=${finalized}`;
    return firstValueFrom(this.http.get<SearchResult<InvoiceDTO>>(urlAltered).pipe(map(r => r.data)));
  }


  async downloadUbl(id: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/invoice/:id/ubl").replace(':id', id + '');
    return firstValueFrom(this.http.get<void>(urlAltered).pipe(map(r => r.data)));
  }


  async finalize(id: string, requestBody: void): Promise<InvoiceDTO> {
    let urlAltered = this.interceptUrl("api/invoice/:id/finalize").replace(':id', id + '');
    return firstValueFrom(this.http.put<InvoiceDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async createFromTransaction(sellerPaymentOrderId: string, requestBody: void): Promise<InvoiceDTO> {
    let urlAltered = this.interceptUrl("api/invoice/from-transaction/:sellerPaymentOrderId").replace(':sellerPaymentOrderId', sellerPaymentOrderId + '');
    return firstValueFrom(this.http.post<InvoiceDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


}
