/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { ItemPriceDTO, ItemAddDTO, ItemDTO } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class ItemControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async deletePrice(itemId: string, priceId: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/item/:id/prices/:priceId").replace(':itemId', itemId + '').replace(':priceId', priceId + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


  async getDefaultPrices(id: string): Promise<ItemPriceDTO[]> {
    let urlAltered = this.interceptUrl("api/item/:id/prices/default").replace(':id', id + '');
    return firstValueFrom(this.http.get<ItemPriceDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async getLatestPrices(id: string): Promise<ItemPriceDTO[]> {
    let urlAltered = this.interceptUrl("api/item/:id/prices/latest").replace(':id', id + '');
    return firstValueFrom(this.http.get<ItemPriceDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async addDefaultPrice(id: string, requestBody: ItemPriceDTO): Promise<ItemPriceDTO> {
    let urlAltered = this.interceptUrl("api/item/:id/prices/default").replace(':id', id + '');
    return firstValueFrom(this.http.post<ItemPriceDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async add(requestBody: ItemAddDTO): Promise<ItemDTO> {
    let urlAltered = this.interceptUrl("api/item");
    return firstValueFrom(this.http.post<ItemDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async fetchAll(id: string | undefined, entityGroup: string | undefined, entityName: string | undefined, name: string | undefined, showOnlyUserOwned: "true" | "false" | undefined, entityId: string | undefined, entityOwnershipGroupId: string | undefined, itemClass: string | undefined): Promise<ItemDTO[]> {
    let urlAltered = this.interceptUrl("api/item") + '?' + `id=${id}` + '&' + `entityGroup=${entityGroup}` + '&' + `entityName=${entityName}` + '&' + `name=${name}` + '&' + `showOnlyUserOwned=${showOnlyUserOwned}` + '&' + `entityId=${entityId}` + '&' + `entityOwnershipGroupId=${entityOwnershipGroupId}` + '&' + `itemClass=${itemClass}`;
    return firstValueFrom(this.http.get<ItemDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async search(id: string | undefined, entityGroup: string | undefined, entityName: string | undefined, name: string | undefined, showOnlyUserOwned: "true" | "false" | undefined, entityId: string | undefined, entityOwnershipGroupId: string | undefined, itemClass: string | undefined): Promise<ItemDTO> {
    let urlAltered = this.interceptUrl("api/item/_search") + '?' + `id=${id}` + '&' + `entityGroup=${entityGroup}` + '&' + `entityName=${entityName}` + '&' + `name=${name}` + '&' + `showOnlyUserOwned=${showOnlyUserOwned}` + '&' + `entityId=${entityId}` + '&' + `entityOwnershipGroupId=${entityOwnershipGroupId}` + '&' + `itemClass=${itemClass}`;
    return firstValueFrom(this.http.get<ItemDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchOne(id: String): Promise<ItemDTO> {
    let urlAltered = this.interceptUrl("api/item/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<ItemDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async add(requestBody: ItemAddDTO): Promise<ItemDTO> {
    let urlAltered = this.interceptUrl("api/item");
    return firstValueFrom(this.http.post<ItemDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async edit(requestBody: ItemAddDTO): Promise<ItemDTO> {
    let urlAltered = this.interceptUrl("api/item");
    return firstValueFrom(this.http.put<ItemDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async remove(id: String): Promise<void> {
    let urlAltered = this.interceptUrl("api/item/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


}
