/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { ItemTaxDTO } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class ItemTaxControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async fetchAll(entityOwnershipGroupId: string | undefined, entityIds: string[] | undefined, admin: "true" | "false" | undefined, taxName: string, ownerUserId: string | undefined, visibility: "PUBLIC" | "PRIVATE" | "NONE" | undefined): Promise<ItemTaxDTO[]> {
    let urlAltered = this.interceptUrl("api/item-tax") + '?' + `entityOwnershipGroupId=${entityOwnershipGroupId}` + '&' + `entityIds=${entityIds}` + '&' + `admin=${admin}` + '&' + `taxName=${taxName}` + '&' + `ownerUserId=${ownerUserId}` + '&' + `visibility=${visibility}`;
    return firstValueFrom(this.http.get<ItemTaxDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async search(entityOwnershipGroupId: string | undefined, entityIds: string[] | undefined, admin: "true" | "false" | undefined, taxName: string, ownerUserId: string | undefined, visibility: "PUBLIC" | "PRIVATE" | "NONE" | undefined): Promise<ItemTaxDTO> {
    let urlAltered = this.interceptUrl("api/item-tax/_search") + '?' + `entityOwnershipGroupId=${entityOwnershipGroupId}` + '&' + `entityIds=${entityIds}` + '&' + `admin=${admin}` + '&' + `taxName=${taxName}` + '&' + `ownerUserId=${ownerUserId}` + '&' + `visibility=${visibility}`;
    return firstValueFrom(this.http.get<ItemTaxDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchOne(id: String): Promise<ItemTaxDTO> {
    let urlAltered = this.interceptUrl("api/item-tax/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<ItemTaxDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async add(requestBody: ItemTaxDTO): Promise<ItemTaxDTO> {
    let urlAltered = this.interceptUrl("api/item-tax");
    return firstValueFrom(this.http.post<ItemTaxDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async edit(requestBody: ItemTaxDTO): Promise<ItemTaxDTO> {
    let urlAltered = this.interceptUrl("api/item-tax");
    return firstValueFrom(this.http.put<ItemTaxDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async remove(id: String): Promise<void> {
    let urlAltered = this.interceptUrl("api/item-tax/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


}
