/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { PaymentInitDTO, PaymentDTO, PaymentCaptureInfoDTO, PaymentChannelStatusDTO, PaymentFullDTO, PaymentItemDto, TaxDTO } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class PaymentControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async initialize(requestBody: PaymentInitDTO): Promise<PaymentDTO> {
    let urlAltered = this.interceptUrl("api/payment");
    return firstValueFrom(this.http.post<PaymentDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async startOperation(id: string, requestBody: PaymentCaptureInfoDTO): Promise<PaymentChannelStatusDTO> {
    let urlAltered = this.interceptUrl("api/payment/:id/operation/start").replace(':id', id + '');
    return firstValueFrom(this.http.post<PaymentChannelStatusDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async checkOperation(id: string, requestBody: void): Promise<PaymentDTO> {
    let urlAltered = this.interceptUrl("api/payment/:id/operation/check").replace(':id', id + '');
    return firstValueFrom(this.http.post<PaymentDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async fetchPaymentInformation(id: string): Promise<PaymentDTO> {
    let urlAltered = this.interceptUrl("api/payment/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<PaymentDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchPaymentFull(id: string): Promise<PaymentFullDTO> {
    let urlAltered = this.interceptUrl("api/payment/:id/full").replace(':id', id + '');
    return firstValueFrom(this.http.get<PaymentFullDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchItems(id: string): Promise<PaymentItemDto[]> {
    let urlAltered = this.interceptUrl("api/payment/:id/item").replace(':id', id + '');
    return firstValueFrom(this.http.get<PaymentItemDto[]>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchTaxes(id: string): Promise<TaxDTO[]> {
    let urlAltered = this.interceptUrl("api/payment/:id/tax").replace(':id', id + '');
    return firstValueFrom(this.http.get<TaxDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async cancelPayment(id: string): Promise<PaymentDTO> {
    let urlAltered = this.interceptUrl("api/payment/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<PaymentDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async confirmOpenPayment(id: string, requestBody: { sellerAccountId: string; }): Promise<PaymentDTO> {
    let urlAltered = this.interceptUrl("api/payment/:id/confirm").replace(':id', id + '');
    return firstValueFrom(this.http.post<PaymentDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


}
