/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { PaymentDTO, AccountDTO } from '@tk-postral/payment-common';
import { RawSearchResult } from '@ubs-platform/crud-base-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class PaymentSearchControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async fetchAll(id: string | undefined, type: "PURCHASE" | "REFUND" | undefined, customerAccountId: string | undefined, sellerAccountIds: string | undefined, paymentChannelIds: string | undefined, paymentStatus: string | undefined, currency: string | undefined, dateFrom: string | undefined, dateTo: string | undefined, searchSide: "USER" | "ADMIN" | undefined, page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined): Promise<PaymentDTO[]> {
    let urlAltered = this.interceptUrl("api/payment") + '?' + `id=${id}` + '&' + `type=${type}` + '&' + `customerAccountId=${customerAccountId}` + '&' + `sellerAccountIds=${sellerAccountIds}` + '&' + `paymentChannelIds=${paymentChannelIds}` + '&' + `paymentStatus=${paymentStatus}` + '&' + `currency=${currency}` + '&' + `dateFrom=${dateFrom}` + '&' + `dateTo=${dateTo}` + '&' + `searchSide=${searchSide}` + '&' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}`;
    return firstValueFrom(this.http.get<PaymentDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async searchAll(id: string | undefined, type: "PURCHASE" | "REFUND" | undefined, customerAccountId: string | undefined, sellerAccountIds: string | undefined, paymentChannelIds: string | undefined, paymentStatus: string | undefined, currency: string | undefined, dateFrom: string | undefined, dateTo: string | undefined, searchSide: "USER" | "ADMIN" | undefined, page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined): Promise<RawSearchResult<PaymentDTO>> {
    let urlAltered = this.interceptUrl("api/payment/_search") + '?' + `id=${id}` + '&' + `type=${type}` + '&' + `customerAccountId=${customerAccountId}` + '&' + `sellerAccountIds=${sellerAccountIds}` + '&' + `paymentChannelIds=${paymentChannelIds}` + '&' + `paymentStatus=${paymentStatus}` + '&' + `currency=${currency}` + '&' + `dateFrom=${dateFrom}` + '&' + `dateTo=${dateTo}` + '&' + `searchSide=${searchSide}` + '&' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}`;
    return firstValueFrom(this.http.get<RawSearchResult<PaymentDTO>>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchRelatedAccounts(relatedAccountIds: string[] | undefined, selectFrom: "SOURCE" | "TARGET" | "BOTH", filterRelatedAccountIdsIn: "SOURCE" | "TARGET" | "BOTH"): Promise<AccountDTO[]> {
    let urlAltered = this.interceptUrl("api/payment/related-accounts") + '?' + `relatedAccountIds=${relatedAccountIds}` + '&' + `selectFrom=${selectFrom}` + '&' + `filterRelatedAccountIdsIn=${filterRelatedAccountIdsIn}`;
    return firstValueFrom(this.http.get<AccountDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


}
