/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { PaymentItemDto } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class PaymentItemSearchControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async searchItems(id: string | undefined, itemId: string | undefined, name: string | undefined, variation: string | undefined, sellerAccountId: string | undefined, entityGroup: string | undefined, entityId: string | undefined, entityName: string | undefined, entityOwnerAccountId: string | undefined, paymentId: string | undefined): Promise<PaymentItemDto[]> {
    let urlAltered = this.interceptUrl("api/payment-items") + '?' + `id=${id}` + '&' + `itemId=${itemId}` + '&' + `name=${name}` + '&' + `variation=${variation}` + '&' + `sellerAccountId=${sellerAccountId}` + '&' + `entityGroup=${entityGroup}` + '&' + `entityId=${entityId}` + '&' + `entityName=${entityName}` + '&' + `entityOwnerAccountId=${entityOwnerAccountId}` + '&' + `paymentId=${paymentId}`;
    return firstValueFrom(this.http.get<PaymentItemDto[]>(urlAltered).pipe(map(r => r.data)));
  }


}
