/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { CreateRefundRequestDTO, RefundRequestDTO } from '@tk-postral/payment-common';
import { RawSearchResult } from '@ubs-platform/crud-base-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class RefundControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async createRefundRequest(requestBody: CreateRefundRequestDTO): Promise<RefundRequestDTO> {
    let urlAltered = this.interceptUrl("api/refund/request");
    return firstValueFrom(this.http.post<RefundRequestDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async approveRefundRequest(id: string, requestBody: void): Promise<RefundRequestDTO> {
    let urlAltered = this.interceptUrl("api/refund/request/:id/approve").replace(':id', id + '');
    return firstValueFrom(this.http.post<RefundRequestDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async rejectRefundRequest(id: string, requestBody: void): Promise<RefundRequestDTO> {
    let urlAltered = this.interceptUrl("api/refund/request/:id/reject").replace(':id', id + '');
    return firstValueFrom(this.http.post<RefundRequestDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async searchRefundRequests(page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined, status: "PENDING" | "APPROVED" | "REJECTED" | undefined, paymentId: string | undefined, sellerAccountId: string | undefined, mode: "USER" | "ADMIN"): Promise<RawSearchResult<RefundRequestDTO>> {
    let urlAltered = this.interceptUrl("api/refund/request/_search") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}` + '&' + `status=${status}` + '&' + `paymentId=${paymentId}` + '&' + `sellerAccountId=${sellerAccountId}` + '&' + `mode=${mode}`;
    return firstValueFrom(this.http.get<RawSearchResult<RefundRequestDTO>>(urlAltered).pipe(map(r => r.data)));
  }


  async getRefundRequestById(id: string): Promise<RefundRequestDTO> {
    let urlAltered = this.interceptUrl("api/refund/request/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<RefundRequestDTO>(urlAltered).pipe(map(r => r.data)));
  }


}
