/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { ReportDTO, ReportQueryDTO } from '@tk-postral/payment-common';
import { RawSearchResult } from '@ubs-platform/crud-base-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class ReportQueryControllerService {
  readonly basePath = process.env.TESTO_POSTRAL_URL || '';;
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async getReports(id: string): Promise<ReportDTO[]> {
    let urlAltered = this.interceptUrl("api/report-query/:id/reports").replace(':id', id + '');
    return firstValueFrom(this.http.get<ReportDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async searchReports(id: string, page: number | undefined, size: number | undefined, hideArchived: string | undefined): Promise<RawSearchResult<ReportDTO>> {
    let urlAltered = this.interceptUrl("api/report-query/:id/reports/_search").replace(':id', id + '') + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `hideArchived=${hideArchived}`;
    return firstValueFrom(this.http.get<RawSearchResult<ReportDTO>>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchAll(ownerAccountId: string | undefined, admin: "true" | "false"): Promise<ReportQueryDTO[]> {
    let urlAltered = this.interceptUrl("api/report-query") + '?' + `ownerAccountId=${ownerAccountId}` + '&' + `admin=${admin}`;
    return firstValueFrom(this.http.get<ReportQueryDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async search(ownerAccountId: string | undefined, admin: "true" | "false"): Promise<ReportQueryDTO> {
    let urlAltered = this.interceptUrl("api/report-query/_search") + '?' + `ownerAccountId=${ownerAccountId}` + '&' + `admin=${admin}`;
    return firstValueFrom(this.http.get<ReportQueryDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchOne(id: string): Promise<ReportQueryDTO> {
    let urlAltered = this.interceptUrl("api/report-query/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<ReportQueryDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async add(requestBody: ReportQueryDTO): Promise<ReportQueryDTO> {
    let urlAltered = this.interceptUrl("api/report-query");
    return firstValueFrom(this.http.post<ReportQueryDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async edit(requestBody: ReportQueryDTO): Promise<ReportQueryDTO> {
    let urlAltered = this.interceptUrl("api/report-query");
    return firstValueFrom(this.http.put<ReportQueryDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async remove(id: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/report-query/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


}
