/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { ReportReconstructionDTO, ReportFullDTO, ReportDTO } from '@tk-postral/payment-common';
import { RawSearchResult } from '@ubs-platform/crud-base-common';



import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class ReportControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async reconstructReport(requestBody: ReportReconstructionDTO): Promise<void> {
    let urlAltered = this.interceptUrl("api/report/reconstruct");
    return firstValueFrom(this.http.post<void>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async fetchInProgress(requestBody: { reportIds: string[]; }): Promise<any> {
    let urlAltered = this.interceptUrl("api/report/fetch-in-progress");
    return firstValueFrom(this.http.post<any>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async getReportById(id: string): Promise<ReportFullDTO> {
    let urlAltered = this.interceptUrl("api/report/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<ReportFullDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async searchReports(page: number, size: number, sortBy: string | undefined, sortRotation: "desc" | "asc" | undefined, queryId: string | undefined, ownerAccountIds: string | string[] | undefined, includeArchived: boolean | "true" | "false" | undefined, periodLabel: string | undefined, admin: "true" | "false" | undefined): Promise<SearchResult<ReportDTO>> {
    let urlAltered = this.interceptUrl("api/report/_search") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}` + '&' + `queryId=${queryId}` + '&' + `ownerAccountIds=${ownerAccountIds}` + '&' + `includeArchived=${includeArchived}` + '&' + `periodLabel=${periodLabel}` + '&' + `admin=${admin}`;
    return firstValueFrom(this.http.get<SearchResult<ReportDTO>>(urlAltered).pipe(map(r => r.data)));
  }


}
