/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { PaymentTransactionDTO } from '@tk-postral/payment-common';
import { RawSearchResult } from '@ubs-platform/crud-base-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class TransactionSearchControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async fetchAll(page: number, size: number, sortBy: string, sortRotation: "desc" | "asc", id: string | undefined, paymentId: string | undefined, targetAccountIds: string | undefined, sourceAccountIds: string | undefined, paymentStatus: import("/home/huseyin/dev/tk-ubs/postralmona/libs/payment-common/src/type/status").PaymentStatus | undefined, currency: string | undefined, dateFrom: string | undefined, dateTo: string | undefined, admin: "true" | "false"): Promise<PaymentTransactionDTO[]> {
    let urlAltered = this.interceptUrl("api/seller-payment-order") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}` + '&' + `id=${id}` + '&' + `paymentId=${paymentId}` + '&' + `targetAccountIds=${targetAccountIds}` + '&' + `sourceAccountIds=${sourceAccountIds}` + '&' + `paymentStatus=${paymentStatus}` + '&' + `currency=${currency}` + '&' + `dateFrom=${dateFrom}` + '&' + `dateTo=${dateTo}` + '&' + `admin=${admin}`;
    return firstValueFrom(this.http.get<PaymentTransactionDTO[]>(urlAltered).pipe(map(r => r.data)));
  }


  async searchAll(page: number, size: number, sortBy: string, sortRotation: "desc" | "asc", id: string | undefined, paymentId: string | undefined, targetAccountIds: string | undefined, sourceAccountIds: string | undefined, paymentStatus: import("/home/huseyin/dev/tk-ubs/postralmona/libs/payment-common/src/type/status").PaymentStatus | undefined, currency: string | undefined, dateFrom: string | undefined, dateTo: string | undefined, admin: "true" | "false"): Promise<RawSearchResult<PaymentTransactionDTO>> {
    let urlAltered = this.interceptUrl("api/seller-payment-order/_search") + '?' + `page=${page}` + '&' + `size=${size}` + '&' + `sortBy=${sortBy}` + '&' + `sortRotation=${sortRotation}` + '&' + `id=${id}` + '&' + `paymentId=${paymentId}` + '&' + `targetAccountIds=${targetAccountIds}` + '&' + `sourceAccountIds=${sourceAccountIds}` + '&' + `paymentStatus=${paymentStatus}` + '&' + `currency=${currency}` + '&' + `dateFrom=${dateFrom}` + '&' + `dateTo=${dateTo}` + '&' + `admin=${admin}`;
    return firstValueFrom(this.http.get<RawSearchResult<PaymentTransactionDTO>>(urlAltered).pipe(map(r => r.data)));
  }


  async fetchById(id: string): Promise<PaymentTransactionDTO> {
    let urlAltered = this.interceptUrl("api/seller-payment-order/:id").replace(':id', id + '');
    return firstValueFrom(this.http.get<PaymentTransactionDTO>(urlAltered).pipe(map(r => r.data)));
  }


}
