/**
 * This file is auto-generated by MonaXr tool.
 * Generated files can have mistakes. Please verify the generated code before using.
 * Feel free to feedback any issues to https://github.com/ubs-platform/ubs-mona-mr
 * Generated on: 2026-05-09T10:40:29.248Z
 */
import { WebhookConfigDTO, WebhookConfigCreateDTO, WebhookConfigUpdateDTO } from '@tk-postral/payment-common';


import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { map } from 'rxjs/operators';

@Injectable()
export class WebhookConfigControllerService {
  readonly basePath = '';
  constructor(private http: HttpService) {}

  interceptUrl(url: string): string {
    // you can modify url here if needed
    return this.basePath + (!url || this.basePath.endsWith("/") ? "" : "/") + url;
  }



  async getByAccountId(accountId: string): Promise<WebhookConfigDTO> {
    let urlAltered = this.interceptUrl("api/webhook-config") + '?' + `accountId=${accountId}`;
    return firstValueFrom(this.http.get<WebhookConfigDTO>(urlAltered).pipe(map(r => r.data)));
  }


  async create(requestBody: WebhookConfigCreateDTO): Promise<WebhookConfigDTO> {
    let urlAltered = this.interceptUrl("api/webhook-config");
    return firstValueFrom(this.http.post<WebhookConfigDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async update(id: string, requestBody: WebhookConfigUpdateDTO): Promise<WebhookConfigDTO> {
    let urlAltered = this.interceptUrl("api/webhook-config/:id").replace(':id', id + '');
    return firstValueFrom(this.http.put<WebhookConfigDTO>(urlAltered, requestBody).pipe(map(r => r.data)));
  }


  async delete(id: string): Promise<void> {
    let urlAltered = this.interceptUrl("api/webhook-config/:id").replace(':id', id + '');
    return firstValueFrom(this.http.delete<void>(urlAltered).pipe(map(r => r.data)));
  }


}
