worker_processes auto;

events {
    worker_connections 2048;
}

http {
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        listen 80 default_server;
        
        location / {
            root /usr/share/nginx/html;
            include  /etc/nginx/mime.types;
            try_files $uri $uri/ /index.html?$args;
        }

        location /api/exams {
            rewrite ^/(.*) /$1 break;
            proxy_pass http://ubs-dev-monolith:3000/;
        }

        location /api/users {
            rewrite /api/users/(.*) /api/$1 break;
            proxy_pass http://ubs-dev-monolith:3000/;
        }

        location /api/file {
            rewrite ^/(.*) /$1 break;
            proxy_pass http://ubs-dev-monolith:3000/;
        }

        location /api/feedback {
            rewrite /api/feedback/(.*) /api/$1 break;
            proxy_pass http://ubs-dev-monolith:3000/;
        }

        location /api/notify {
            rewrite /api/notify/(.*) /api/$1 break;
            proxy_pass http://ubs-dev-monolith:3000/;
        }

        location /api/social {
            rewrite /api/social/(.*) /api/$1 break;
            proxy_pass http://ubs-dev-monolith:3000/;
        }
    }

}
